export const enumTokenState = {
  IDLE: 'IDLE',
  HOVER_FALL: 'HOVER_FALL',
  HOVER_FALL_ACTIVE: 'HOVER_FALL_ACTIVE',
  HOVER_RISE: 'HOVER_RISE',
  HOVER_RISE_ACTIVE: 'HOVER_RISE_ACTIVE'
}

export const enumDriveState = {
  IDLE: 'IDLE',
  DRIVE: 'DRIVE',
  JUMP_FALL: 'JUMP_FALL',
  JUMP_FALL_ACTIVE: 'JUMP_FALL_ACTIVE',
  JUMP_RISE: 'JUMP_RISE',
  JUMP_RISE_ACTIVE: 'JUMP_RISE_ACTIVE'
}

export const enumGameObjectTypes = {
  TOKEN: 'TOKEN',
  GROUND: 'GROUND',
  TRUCK: 'TRUCK',

}
